import { useState, useEffect, useRef } from 'react';
import './LandingPage.css';
import InfraSimulation from '../components/InfraSimulation';
import NeuralHeroCanvas from '../components/NeuralHeroCanvas';
import ParticleMesh from '../components/ParticleMesh';
import AnimatedCounter from '../components/AnimatedCounter';

const NAV_LINKS = ['Features', 'Ecosystem', 'SDK', 'Pricing', 'Docs'];

const FEATURES = [
  { icon: '🤖', color: 'rgba(155,89,255,0.12)', title: 'Agent Fleet Monitoring', desc: 'Track 100+ AI agents across departments. Real-time status, execution history, and performance metrics in one dashboard.' },
  { icon: '🧠', color: 'rgba(77,124,255,0.12)', title: 'Knowledge Brain', desc: 'Persistent memory across all AI sessions. Auto-capture decisions, discoveries, and architectural changes. Never lose context again.' },
  { icon: '🕸️', color: 'rgba(0,212,255,0.12)', title: 'Knowledge Graph', desc: 'Interactive force-directed visualization of your codebase relationships. See how agents, files, and workflows connect.' },
  { icon: '📦', color: 'rgba(0,230,138,0.12)', title: 'Multi-Workspace', desc: 'Manage 50+ repos from a single pane of glass. Git status, branches, dirty files, and context routing across projects.' },
  { icon: '⚡', color: 'rgba(255,159,67,0.12)', title: 'Auto-Capture Hooks', desc: 'Git post-commit hooks auto-log every change. Scheduled brain refresh keeps knowledge items fresh without manual work.' },
  { icon: '🔧', color: 'rgba(255,107,157,0.12)', title: 'SDK & API Access', desc: 'npm install @stoic/agentos-sdk — wrap any agent in 3 lines of code. Full REST API with API key management and webhook integrations.' },
];

const PRICING = [
  { name: 'Free', desc: 'For solo developers', price: '$0', period: '', features: ['2 workspaces', '5 agents', '10,000 obs/mo', '5 knowledge items', '3 git hook repos', 'Read-only API', 'Community support'], disabled: ['Knowledge Graph', 'Trace Timeline', 'SSO/SAML'], cta: 'Get Started Free', style: 'default' },
  { name: 'Pro', desc: 'For power users', price: '$49', period: '/mo', features: ['10 workspaces', '25 agents', '100,000 obs/mo', '25 knowledge items', '15 git hook repos', '5 team members', 'Knowledge Graph', 'Trace Timeline', 'Full API access', 'Email support (48h)'], disabled: ['SSO/SAML', 'Self-hosted'], cta: 'Start 14-Day Trial', style: 'default' },
  { name: 'Team', desc: 'For growing teams', price: '$299', period: '/mo', features: ['Unlimited workspaces', '100 agents', 'Unlimited observations', 'Unlimited knowledge items', 'Unlimited git hooks', '15 team members', 'Knowledge Graph', 'Trace Timeline', 'Full API access', 'Priority support (4h)'], disabled: ['SSO/SAML', 'Self-hosted'], cta: 'Start 14-Day Trial', style: 'featured' },
  { name: 'Enterprise', desc: 'For organizations', price: 'Custom', period: '', features: ['Everything in Team', 'Unlimited agents', 'Unlimited observations', 'Unlimited members', 'SSO/SAML', 'Self-hosted (coming soon)', 'Custom integrations', 'Dedicated CSM', 'SLA guarantee', 'Audit logs'], disabled: [], cta: 'Contact Sales', style: 'default' },
];

const COMPARE = [
  { feature: 'Agent Fleet Monitoring', us: '✅', crewai: '✅', langfuse: '❌', agentops: '🟡' },
  { feature: 'Knowledge Brain + Memory', us: '✅', crewai: '❌', langfuse: '🟡', agentops: '🟡' },
  { feature: 'Knowledge Graph', us: '✅', crewai: '❌', langfuse: '❌', agentops: '❌' },
  { feature: 'Multi-Repo Workspace', us: '✅', crewai: '❌', langfuse: '❌', agentops: '❌' },
  { feature: 'Auto-Capture (Git Hooks)', us: '✅', crewai: '❌', langfuse: '🟡', agentops: '🟡' },
  { feature: 'Brand/Voice Vault', us: '✅', crewai: '❌', langfuse: '❌', agentops: '❌' },
  { feature: 'Financial AI Agents', us: '🔜', crewai: '❌', langfuse: '❌', agentops: '❌' },
  { feature: 'Visual Dashboard', us: '✅', crewai: '🟡', langfuse: '✅', agentops: '🟡' },
  { feature: 'Open-Source Core', us: '✅', crewai: '✅', langfuse: '✅', agentops: '✅' },
];

const ECOSYSTEM = [
  {
    icon: '📊', name: 'StoicCRM Growth', tagline: 'AI-Powered Sales Command Center',
    desc: '12 autonomous sales agents running lead scoring, outreach sequences, and pipeline analytics. The first fleet built on AgentOS.',
    url: 'https://stoicagentos.com/dashboard', badge: 'Live',
    gradient: 'linear-gradient(135deg, rgba(155,89,255,0.15), rgba(77,124,255,0.08))', border: 'rgba(155,89,255,0.25)',
  },
  {
    icon: '🧠', name: 'Command Center', tagline: 'Second Brain for Agent Fleets',
    desc: '23 agents, 14 workspaces, knowledge graph, persistent memory engine. The orchestration hub that connects everything.',
    url: 'https://stoicagentos.com/dashboard', badge: 'Live',
    gradient: 'linear-gradient(135deg, rgba(0,212,255,0.15), rgba(0,230,138,0.08))', border: 'rgba(0,212,255,0.25)',
  },
  {
    icon: '🎬', name: 'Fetok Autoposter', tagline: 'Cinematic Content Automation',
    desc: 'Autonomous TikTok pipeline: FFmpeg rendering + TTS narration + OBS streaming. 100K+ views generated by AI agents.',
    url: 'https://github.com/benjaminkernbaum-ux', badge: 'Open Source',
    gradient: 'linear-gradient(135deg, rgba(255,107,157,0.15), rgba(255,159,67,0.08))', border: 'rgba(255,107,157,0.25)',
  },
];

const SDK_CODE = `<span class="kw">import</span> { AgentOS } <span class="kw">from</span> <span class="str">'@stoic/agentos-sdk'</span>;

<span class="cm">// Initialize with your API key</span>
<span class="kw">const</span> os = <span class="kw">new</span> <span class="fn">AgentOS</span>({
  apiKey: <span class="str">'sk_live_xxx'</span>,
  workspace: <span class="str">'my-saas-backend'</span>,
});

<span class="cm">// Wrap any agent — auto-captures start/end/errors</span>
<span class="kw">const</span> invoiceAgent = os.<span class="fn">wrapAgent</span>(<span class="str">'invoice-processor'</span>, <span class="kw">async</span> (input) <span class="op">=></span> {
  <span class="kw">const</span> result = <span class="kw">await</span> <span class="fn">processInvoice</span>(input);
  <span class="kw">return</span> result;
});

<span class="cm">// Manual capture for decisions & discoveries</span>
os.<span class="fn">capture</span>({
  type: <span class="str">'decision'</span>,
  title: <span class="str">'Switched to GPT-4o-mini'</span>,
  content: <span class="str">'Reduced cost by 40% with no quality loss'</span>,
  agent: <span class="str">'content-writer'</span>,
});`;

/* ═══════════════════════════════════════════
   SCROLL REVEAL HOOK
   ═══════════════════════════════════════════ */
function useScrollReveal() {
  const ref = useRef(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            // Reveal all children with .section-reveal
            e.target.querySelectorAll('.section-reveal').forEach((child, i) => {
              setTimeout(() => child.classList.add('visible'), i * 100);
            });
            // Also reveal self if it has the class
            if (e.target.classList.contains('section-reveal')) {
              e.target.classList.add('visible');
            }
          }
        });
      },
      { threshold: 0.1 }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return ref;
}

/* ═══════════════════════════════════════════
   LANDING PAGE
   ═══════════════════════════════════════════ */
export default function LandingPage() {
  const [scrolled, setScrolled] = useState(false);

  // Section refs for scroll reveal
  const infraRef = useScrollReveal();
  const metricsRef = useScrollReveal();
  const featuresRef = useScrollReveal();
  const sdkRef = useScrollReveal();
  const compareRef = useScrollReveal();
  const ecoRef = useScrollReveal();
  const pricingRef = useScrollReveal();
  const ctaRef = useScrollReveal();

  useEffect(() => {
    document.title = 'Stoic AgentOS — AI Agent Operations Platform';
  }, []);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 30);
    window.addEventListener('scroll', onScroll);
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  return (
    <div className="landing">
      {/* ── NAV ── */}
      <nav className={`nav ${scrolled ? 'scrolled' : ''}`}>
        <div className="nav-inner">
          <div className="nav-logo">
            <div className="nav-logo-icon">⚡</div>
            <span>Stoic <span style={{ color: 'var(--accent-purple)' }}>AgentOS</span></span>
          </div>
          <div className="nav-links">
            {NAV_LINKS.map(l => <a key={l} className="nav-link" href={l === 'Docs' ? '/docs' : `#${l.toLowerCase()}`}>{l}</a>)}
            <a className="nav-link" href="/login">Sign In</a>
            <button className="btn btn-primary btn-sm" onClick={() => window.location.href = '/signup'}>Get Started Free</button>
          </div>
        </div>
      </nav>

      {/* ══════════════════════════════════
           HERO — Neural Network Canvas
         ══════════════════════════════════ */}
      <section className="hero">
        <NeuralHeroCanvas />
        <div className="container">
          <div className="hero-badge animate-in">
            <span className="hero-badge-dot" />
            $11.6B market · Backed by real production use
          </div>
          <h1 className="animate-in delay-1">
            Your AI Agents Need<br />
            a <span className="gradient-text">Command Center</span>
          </h1>
          <p className="hero-sub animate-in delay-2">
            Monitor, orchestrate, and scale your AI agent fleet from a single premium dashboard. 
            Knowledge persistence, auto-capture, and multi-workspace management — built for teams shipping AI.
          </p>
          <div className="hero-cta animate-in delay-3">
            <button className="btn btn-primary btn-lg" onClick={() => window.location.href = '/signup'}>
              🚀 Start Free — No Credit Card
            </button>
            <button className="btn btn-secondary btn-lg" onClick={() => document.getElementById('sdk')?.scrollIntoView({ behavior: 'smooth' })}>
              View SDK →
            </button>
          </div>
          <div className="hero-metrics animate-in delay-4">
            <div className="hero-metric">
              <div className="hero-metric-value" style={{ color: 'var(--accent-purple)' }}>23</div>
              <div className="hero-metric-label">Agents Managed</div>
            </div>
            <div className="hero-metric">
              <div className="hero-metric-value" style={{ color: 'var(--accent-cyan)' }}>14</div>
              <div className="hero-metric-label">Workspaces</div>
            </div>
            <div className="hero-metric">
              <div className="hero-metric-value" style={{ color: 'var(--accent-green)' }}>$184K</div>
              <div className="hero-metric-label">Annual Savings</div>
            </div>
            <div className="hero-metric">
              <div className="hero-metric-value" style={{ color: 'var(--accent-orange)' }}>324</div>
              <div className="hero-metric-label">Observations</div>
            </div>
          </div>
        </div>
        {/* Scroll indicator */}
        <div className="scroll-indicator">
          <span>Scroll to explore</span>
          <svg viewBox="0 0 24 24"><polyline points="7 13 12 18 17 13" /><polyline points="7 6 12 11 17 6" /></svg>
        </div>
      </section>

      {/* ══════════════════════════════════
           INFRASTRUCTURE SIMULATION
         ══════════════════════════════════ */}
      <section className="section" style={{ paddingTop: 0 }} ref={infraRef}>
        <div className="container-wide section-reveal">
          <InfraSimulation />
        </div>
      </section>

      {/* ══════════════════════════════════
           PERFORMANCE METRICS — Animated Counters
         ══════════════════════════════════ */}
      <section className="section metrics-section" ref={metricsRef}>
        <ParticleMesh particleCount={30} color="#00f0ff" speed={0.15} connectionDistance={100} />
        <div className="container" style={{ position: 'relative', zIndex: 1 }}>
          <div className="section-center section-reveal">
            <div className="section-label">⚡ RAW POWER</div>
            <h2 className="section-title">Built for Production Scale</h2>
            <p className="section-sub">Numbers that speak for themselves.</p>
          </div>
          <div className="metrics-grid section-reveal" style={{ transitionDelay: '0.2s' }}>
            <AnimatedCounter end={12} prefix="< " suffix="ms" color="#00f0ff" label="Response Latency" />
            <AnimatedCounter end={99} suffix=".99%" color="#00ff88" label="Uptime" />
            <AnimatedCounter end={10} suffix="M+" color="#ff00aa" label="Agents Orchestrated" />
            <AnimatedCounter end="∞" color="#ffaa00" label="Scalability" />
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════
           FEATURES
         ══════════════════════════════════ */}
      <section className="section" id="features" ref={featuresRef}>
        <div className="container section-center">
          <div className="section-label section-reveal">⚡ CAPABILITIES</div>
          <h2 className="section-title section-reveal">Everything your AI fleet needs</h2>
          <p className="section-sub section-reveal">
            One platform to monitor agents, persist knowledge, manage workspaces, and automate operations across your entire stack.
          </p>
          <div className="features-grid">
            {FEATURES.map((f, i) => (
              <div key={i} className="feature-card section-reveal" style={{ transitionDelay: `${i * 0.08}s` }}>
                <div className="feature-icon" style={{ background: f.color }}>{f.icon}</div>
                <h3>{f.title}</h3>
                <p>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── SDK ── */}
      <section className="section" id="sdk" style={{ background: 'var(--bg-deep)' }} ref={sdkRef}>
        <div className="container">
          <div className="section-center section-reveal" style={{ marginBottom: 0 }}>
            <div className="section-label">🔧 DEVELOPER SDK</div>
            <h2 className="section-title">3 lines of code to instrument any agent</h2>
            <p className="section-sub">
              npm install, import, wrap. Your agents start reporting to the Command Center immediately.
            </p>
          </div>
          <div className="code-block section-reveal" style={{ transitionDelay: '0.2s' }}>
            <div className="code-header">
              <span className="code-lang">JavaScript / TypeScript</span>
              <button className="code-copy" onClick={() => navigator.clipboard?.writeText('npm install @stoic/agentos-sdk')}>📋 Copy</button>
            </div>
            <div className="code-body" dangerouslySetInnerHTML={{ __html: SDK_CODE }} />
          </div>
          <div className="section-reveal" style={{ display: 'flex', gap: 12, justifyContent: 'center', marginTop: 32, transitionDelay: '0.3s' }}>
            <div className="social-badge">📦 npm install @stoic/agentos-sdk</div>
            <div className="social-badge">🐍 pip install agentos-sdk</div>
          </div>
        </div>
      </section>

      {/* ── COMPARISON ── */}
      <section className="section" id="compare" ref={compareRef}>
        <div className="container section-center">
          <div className="section-label section-reveal">📊 COMPARISON</div>
          <h2 className="section-title section-reveal">Why teams choose AgentOS</h2>
          <p className="section-sub section-reveal">We're the only platform combining agent monitoring + knowledge persistence + workspace management in one dashboard.</p>
          <table className="compare-table section-reveal" style={{ transitionDelay: '0.2s' }}>
            <thead>
              <tr>
                <th>Feature</th>
                <th className="us">⚡ AgentOS</th>
                <th>CrewAI</th>
                <th>Langfuse</th>
                <th>AgentOps</th>
              </tr>
            </thead>
            <tbody>
              {COMPARE.map((row, i) => (
                <tr key={i}>
                  <td>{row.feature}</td>
                  <td className="us">{row.us}</td>
                  <td>{row.crewai}</td>
                  <td>{row.langfuse}</td>
                  <td>{row.agentops}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* ══════════════════════════════════
           ECOSYSTEM — with Particle Background
         ══════════════════════════════════ */}
      <section className="section section-particles" id="ecosystem" ref={ecoRef}>
        <ParticleMesh particleCount={25} color="#9b59ff" speed={0.2} connectionDistance={100} />
        <div className="container section-center" style={{ position: 'relative', zIndex: 1 }}>
          <div className="section-label section-reveal">🌐 ECOSYSTEM</div>
          <h2 className="section-title section-reveal">Built on AgentOS. Deployed on Vercel.</h2>
          <p className="section-sub section-reveal">
            Every product in our ecosystem runs on AgentOS. Real production fleets, not demos.
          </p>
          <div className="features-grid section-reveal" style={{ gridTemplateColumns: 'repeat(3, 1fr)', transitionDelay: '0.2s' }}>
            {ECOSYSTEM.map((e, i) => (
              <a
                key={i}
                href={e.url}
                target="_blank"
                rel="noopener noreferrer"
                className="feature-card"
                style={{
                  animationDelay: `${i * 0.12}s`,
                  background: e.gradient,
                  border: `1px solid ${e.border}`,
                  cursor: 'pointer',
                  textDecoration: 'none',
                  transition: 'transform 0.3s, box-shadow 0.3s',
                }}
                onMouseOver={ev => { ev.currentTarget.style.transform = 'translateY(-6px)'; ev.currentTarget.style.boxShadow = `0 12px 40px ${e.border}`; }}
                onMouseOut={ev => { ev.currentTarget.style.transform = 'translateY(0)'; ev.currentTarget.style.boxShadow = 'none'; }}
              >
                <div style={{ fontSize: '2.2rem', marginBottom: 8 }}>{e.icon}</div>
                <h3 style={{ marginBottom: 2 }}>{e.name}</h3>
                <div style={{ fontSize: '0.75rem', opacity: 0.5, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 12 }}>{e.tagline}</div>
                {e.badge && <span style={{ display: 'inline-block', padding: '2px 8px', borderRadius: 4, fontSize: '0.65rem', fontWeight: 600, background: 'rgba(0,230,138,0.15)', color: '#00e68a', border: '1px solid rgba(0,230,138,0.25)', marginBottom: 8, letterSpacing: 1, textTransform: 'uppercase' }}>{e.badge}</span>}
                <p>{e.desc}</p>
                <div style={{ marginTop: 16, fontSize: '0.75rem', fontFamily: "'JetBrains Mono', monospace", opacity: 0.4 }}>
                  {e.url.replace('https://', '')} →
                </div>
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING ── */}
      <section className="section" id="pricing" style={{ background: 'var(--bg-deep)' }} ref={pricingRef}>
        <div className="container section-center">
          <div className="section-label section-reveal">💎 PRICING</div>
          <h2 className="section-title section-reveal">Start free. Scale when ready.</h2>
          <p className="section-sub section-reveal">No credit card required. Upgrade as your agent fleet grows.</p>
          <div className="pricing-grid section-reveal" style={{ transitionDelay: '0.2s' }}>
            {PRICING.map((p, i) => (
              <div key={i} className={`pricing-card ${p.style}`}>
                <div className="pricing-name">{p.name}</div>
                <div className="pricing-desc">{p.desc}</div>
                <div className="pricing-price">
                  <span className="pricing-amount">{p.price}</span>
                  <span className="pricing-period">{p.period}</span>
                </div>
                <ul className="pricing-features">
                  {p.features.map((f, j) => <li key={j}>{f}</li>)}
                  {p.disabled.map((f, j) => <li key={`d-${j}`} className="disabled">{f}</li>)}
                </ul>
                <button
                  className={`btn ${p.style === 'featured' ? 'btn-primary' : 'btn-secondary'}`}
                  style={{ width: '100%', justifyContent: 'center' }}
                  onClick={() => {
                    if (p.name === 'Enterprise') {
                      window.location.href = 'mailto:benjamin@stoicagentos.com?subject=AgentOS Enterprise Inquiry';
                    } else {
                      window.location.href = '/signup';
                    }
                  }}
                >
                  {p.cta}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════
           CTA — with Particle Background
         ══════════════════════════════════ */}
      <section className="section section-center section-particles" style={{ paddingBottom: 120 }} ref={ctaRef}>
        <ParticleMesh particleCount={35} color="#00ff88" speed={0.25} connectionDistance={110} />
        <div className="container" style={{ position: 'relative', zIndex: 1 }}>
          <h2 className="section-title section-reveal">Ready to command your AI fleet?</h2>
          <p className="section-sub section-reveal" style={{ margin: '0 auto 32px', transitionDelay: '0.1s' }}>
            Join the teams using AgentOS to ship AI faster, with full observability and zero knowledge loss.
          </p>
          <div className="hero-cta section-reveal" style={{ transitionDelay: '0.2s' }}>
            <button className="btn btn-primary btn-lg" onClick={() => window.location.href = '/signup'}>🚀 Get Started Free</button>
            <button className="btn btn-secondary btn-lg" onClick={() => window.location.href = 'mailto:benjamin@stoicagentos.com?subject=AgentOS Demo Request'}>📅 Book a Demo</button>
          </div>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer className="footer">
        <div className="container">
          <div className="footer-grid">
            <div className="footer-brand">
              <h3>⚡ Stoic AgentOS</h3>
              <p>The operating system for AI agent fleets. Monitor, orchestrate, and scale with confidence.</p>
            </div>
            <div className="footer-col">
              <h4>Product</h4>
              <a href="#features">Features</a>
              <a href="#pricing">Pricing</a>
              <a href="#sdk">SDK</a>
              <a href="/docs">Documentation</a>
              <a href="/changelog">Changelog</a>
            </div>
            <div className="footer-col">
              <h4>Company</h4>
              <a href="/about">About</a>
              <a href="/blog">Blog</a>
              <a href="https://github.com/benjaminkernbaum-ux">GitHub</a>
              <a href="https://www.linkedin.com/company/17224756/">LinkedIn</a>
            </div>
            <div className="footer-col">
              <h4>Legal</h4>
              <a href="/privacy">Privacy Policy</a>
              <a href="/terms">Terms of Service</a>
              <a href="/security">Security</a>
            </div>
          </div>
          <div className="footer-bottom">
            <span>© 2026 Stoic AgentOS. All rights reserved.</span>
            <span>Built with ⚡ by Benjamin Kernbaum</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
